### ISSUE TITLE
vscode - markdown - excalidraw - preview : amount of objects or chars issue ?

### ISSUE THREAD

**Issue by sylvainle** [pomdtr/vscode-markdown-kroki#3]
Windows 11 + vscode 1.75.1 + markdow kroki extension v1.0.7
Remote - SSH on wsl2 + Ubuntu 22.04.1 LTS

Hi,

In vscode, preview seems to be limited regarding the amount of objects or chars.

Difference between the two excalidraw diagrams is only two circles but the problem appear with others kind of objects.

See md file and snapshot.

Regards

[test.md](https://github.com/pomdtr/vscode-markdown-kroki/files/10880465/test.md)
![Capture d'écran 2023-03-03 102608](https://user-images.githubusercontent.com/9676962/222683750-29ffbe22-aece-46ed-a1f4-3078da71d88a.png)

**Comment by pomdtr** [comment]
Yes there is a limit in the payload size you can send to kroki.

For your usecase (embedding Excalidraw diagrams in markdown document), you should probably take a look at my Excalidraw extension. It allows you to edit your diagrams as pngs images directly !

**Comment by sylvainle** [comment]
Ok, thanks you, I understand
